version: 2
jobs:
  deploy:
    working_directory: ~/qidb
    docker:
      - image: circleci/ruby:2.4.6
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "f7:6c:a7:3a:38:76:3e:e5:ea:55:36:63:8f:11:74:d2"
      - run:
          name: setup ssh
          command: |
            cp config/ssh_config ~/.ssh/config
            chmod 600 ~/.ssh/config
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update --fix-missing
            sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
      - run:
          name: bundle install
          command: |
           bundle install
      - run:
          name: deploy
          command: bash ./scripts/deploy.sh production release
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - release
